version: 2.1

commands:
  docker_hub_login:
    description: Login to Docker Hub
    steps:
      - run:
          name: Docker Hub login
          command: docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
  configure_git:
    description: Configure Git
    steps:
      - run:
          name: Delete gitconfig
          command: rm -rf ~/.gitconfig
      - run:
          name: Configure Git user
          command: |
            git config --global user.email "ci@healthlabs.com"
            git config --global user.name "Circle CI"
      - run:
          name: Configure Git to use SSH instead of HTTP
          command: |
            git config --global url.git@github.com:.insteadOf git://github.com/

  pull-merge-restore:
    description: "Bring the repository up-to-date with master and restore the cache"
    steps:
      - checkout
      - restore_cache:
          key: composer-{{ checksum "composer.lock" }}
      - configure_git
      - run:
          name: Merge master
          command: git fetch origin && git merge origin/master --no-edit
      - restore_cache:
          key: composer-{{ checksum "composer.lock" }}

  build-and-test:
    description: "Build the project."
    steps:
      - run:
          name: Initialize the project
          command: |
            mkdir -p /tmp/artifacts
            bin/init_project
      - save_cache:
          key: composer-{{ checksum "composer.lock" }}
          paths:
            - ~/.composer/cache
      - run:
          name: Unit Tests
          command: phpunit --log-junit artifacts/phpunit.junit.xml
      - store_test_results:
          path: /tmp/artifacts
      - store_artifacts:
          path: /tmp/artifacts

  configure-php:
    description: Configure the PHP environment.
    parameters:
      version:
        description: The major and minor PHP version to use
        type: string
        default: "7.1"
    steps:
      - run:
          name: Set the PHP runtime version
          command: sed -i "s/PHP_VERSION=[^\n]\+/PHP_VERSION=<< parameters.version >>/" ./docker/lib/images.sh

executors:
  default:
    machine:
      enabled: true

jobs:
  test-php7_1:
    working_directory: /tmp/laravel_sodium
    parallelism: 1
    executor: default
    environment:
      - PATH: /opt/circleci/.pyenv/shims:./bin:./node_modules/.bin:./vendor/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    steps:
      - docker_hub_login
      - pull-merge-restore
      - configure-php:
          version: "7.1"
      - build-and-test
  test-php7_2:
    working_directory: /tmp/laravel_sodium
    parallelism: 1
    executor: default
    environment:
      - PATH: /opt/circleci/.pyenv/shims:./bin:./node_modules/.bin:./vendor/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    steps:
      - pull-merge-restore
      - docker_hub_login
      - configure-php:
          version: "7.2"
      - build-and-test
  test-php7_3:
    working_directory: /tmp/laravel_sodium
    parallelism: 1
    executor: default
    environment:
      - PATH: /opt/circleci/.pyenv/shims:./bin:./node_modules/.bin:./vendor/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    steps:
      - pull-merge-restore
      - docker_hub_login
      - configure-php:
          version: "7.3"
      - build-and-test
  test-php7_4:
    working_directory: /tmp/laravel_sodium
    parallelism: 1
    executor: default
    environment:
      - PATH: /opt/circleci/.pyenv/shims:./bin:./node_modules/.bin:./vendor/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    steps:
      - pull-merge-restore
      - docker_hub_login
      - configure-php:
          version: "7.4"
      - build-and-test

workflows:
  version: 2
  build-and-test:
    jobs:
      - test-php7_1
      - test-php7_2
      - test-php7_3
      - test-php7_4
